version: "3.9"
services:
  db:
    image: mariadb:11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - ./.env

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    env_file:
      - ./client/.env
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
