version: "3.9"
services:
  db:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - ./.env

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    env_file:
      - ./.env.client

volumes:
  db_data:

