FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY prisma ./prisma
COPY src ./src

# Generate Prisma client
RUN npx prisma generate

# Compile TypeScript
RUN npx tsc

EXPOSE 5000

CMD ["sh", "-c" ,"npx prisma migrate deploy && node dist/server.js"]
